//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeterDevice()
        {
            this.MeterReading = new HashSet<MeterReading>();
        }
    
        public int meter_id { get; set; }
        public int account_iаd { get; set; }
        public string service_type { get; set; }
        public string serial_number { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public Nullable<System.DateTime> next_check_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual PersonalAccount PersonalAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterReading> MeterReading { get; set; }
    }
}
