//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int reading_id { get; set; }
        public int meter_id { get; set; }
        public System.DateTime reading_date { get; set; }
        public decimal value { get; set; }
        public string source { get; set; }
        public Nullable<bool> confirmed { get; set; }
    
        public virtual MeterDevice MeterDevice { get; set; }
    }
}
