//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public int account_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public string comment { get; set; }
    
        public virtual PersonalAccount PersonalAccount { get; set; }
    }
}
