//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int request_id { get; set; }
        public int account_id { get; set; }
        public int type_id { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string appointed_master { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
        public Nullable<short> rating { get; set; }
        public string comment_close { get; set; }
    
        public virtual PersonalAccount PersonalAccount { get; set; }
        public virtual RequestType RequestType { get; set; }
    }
}
